---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# trendEcon data repository

We construct economic indicators for Switzerland, based on Google Trends data.

The data is displayed and described at: https://www.trendecon.org

The data is stored as CSV in the [`data`](https://github.com/trendecon/data/tree/master/data) folder.


### Example

The following R code download and displays the main indicator for CH, DE, ant AT:

```{r example, fig.height=3, fig.width=8}

data <- read.csv("https://raw.githubusercontent.com/trendecon/data/master/data/ch/trendecon_sa.csv")
tsbox::ts_plot(data, title = "Switzerland")

data <- read.csv("https://raw.githubusercontent.com/trendecon/data/master/data/de/trendecon_sa.csv")
tsbox::ts_plot(data, title = "Germany")

data <- read.csv("https://raw.githubusercontent.com/trendecon/data/master/data/at/trendecon_sa.csv")
tsbox::ts_plot(data, title = "Austria")

```

